@startuml Séquence Annulation Succès

Actor Student
Participant Phone
Participant Assistant as "Google Assistant"
Participant Application as "Application\n St Louis Ordi"

Student -> Phone: Démarre St Louis Ordi
Phone -> Assistant
Assistant -> Assistant: Recherche de l'application
Assistant -> Application: Initialisation
Application --> Phone: Message: Que puis-je faire pour vous aujourd'hui ?
Application --> Phone: Suggestion 1 : Des ordis libres ?
Application --> Phone: Suggestion 2 : Réservez un ordi ?
Application --> Phone: Suggestion 3 : Annuler une réservation ?

Student -> Phone: Annuler une réservation.
Application -> Phone: Message: Quel est votre numéro d'étudiant ?

Student -> Phone: 1424134
Phone -> Application
Application -> Application: Recherche de l'utilisateur
Application -> Application: Recherche de l'ordi assigné à l'utilisateur
Application -> Application: Libération de l'ordi 
Application -> Phone: Message: Merci Erwan. L'ordinateur n'est plus réservé à votre nom.

@enduml